EXPERIMENT:
  NAME: "res32x4,ShuffleV2_1_5,DKD"
  TAG: "res32x4,ShuffleV2_1_5,DKD"
  PROJECT: "cifar100_SFAKD"
DISTILLER:
  TYPE: "DKD"
  TEACHER: "wrn_40_4"
  STUDENT: "wrn_16_2
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"
DKD:
  BETA: 6.0
LOG:
  WANDB: false
  # WANDB: true