EXPERIMENT:
  NAME: "wrn_40_2,resnet8x4,DKD"
  TAG: "wrn_40_2,resnet8x4,DKD"
  PROJECT: "cifar100_SFAKD"
DISTILLER:
  TYPE: "DKD"
  TEACHER: "wrn_40_2"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  WANDB: false
  # WANDB: true