#704->256
EXPERIMENT:
  NAME: "resnet32x4,ShuffleV2_1_5,oblation1"
  TAG: "resnet32x4,ShuffleV2_1_5,oblation1"
  PROJECT: "cifar100_SFAKD"
DISTILLER:
  TYPE: "SFAKD_oblation1"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV2_1_5"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  # WANDB: false
  WANDB: true


# true: convert the normal CNN to our style
device: 1

DATASET:
  AUTO_AUG: False
  CUT_OUT: False

