EXPERIMENT:
  NAME: "imagenet_r50_mv2"
  TAG: "imagenet_r50_mv2"
  PROJECT: "imagenet_r34_r18"
DATASET:
  TYPE: "imagenet"
  NUM_WORKERS: 32
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "SIMKD_FS"
  TEACHER: "ResNet50"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 2
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"

device: 0

LOG:
  # TENSORBOARD_FREQ: 50
  # SAVE_CHECKPOINT_FREQ: 10
  WANDB: False
