EXPERIMENT:
  NAME: "resnet32x4,MobileNetV2,simkd_baseline"
  TAG: "resnet32x4,MobileNetV2,baseline,3090ti"
  PROJECT: "cifar100_baselines_simkd"
DISTILLER:
  TYPE: "SIMKD"
  TEACHER: "resnet32x4"
  STUDENT: "MobileNetV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  # WANDB: false
  WANDB: true


# true: convert the normal CNN to our style
device: 1

DATASET:
  AUTO_AUG: False
  CUT_OUT: False

