EXPERIMENT:
  NAME: "wrn40_2,wrn_16_2,simkd_baseline"
  TAG: "wrn40_2,wrn_16_2,simkd_baseline,3090ti,78.16_wrn_40_2"
  PROJECT: "cifar100_baselines_simkd"
DISTILLER:
  TYPE: "SIMKD"
  TEACHER: "wrn_40_2"
  STUDENT: "wrn_16_2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  # WANDB: false
  WANDB: true

device: 1

DATASET:
  AUTO_AUG: False
  CUT_OUT: False