EXPERIMENT:
  NAME: "tiny_imagenet_res50_res34,SFAKD"
  TAG: "tiny_imagenet,res50,res34,SFAKD"
  PROJECT: "imagenet_SFAKD"
DATASET:
  TYPE: "tiny_imagenet"
  NUM_WORKERS: 20
  TEST:
    BATCH_SIZE: 128
DISTILLER:
  TYPE: "SFAKD"
  TEACHER: "ResNet50"
  STUDENT: "ResNet34"
SOLVER:
  BATCH_SIZE: 256
  EPOCHS: 100
  LR: 0.2
  LR_DECAY_STAGES: [30, 60, 90]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9
  TYPE: "SGD"

# device: 0

LOG:
  # TENSORBOARD_FREQ: 50
  # SAVE_CHECKPOINT_FREQ: 10
  WANDB: False
