EXPERIMENT:
  NAME: "resnet32x4,vgg8,CATKD"
  TAG: "resnet32x4,vgg8,CATKD"
  PROJECT: "cifar100_SFAKD"
DISTILLER:
  TYPE: "CAT_KD"
  TEACHER: "resnet32x4"
  STUDENT: "vgg8"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  # WANDB: false
  WANDB: true
  
CAT_KD:
  LOSS:
    # Î²
    CAT_loss_weight: 5.
    # the resolution of the transferred CAMs after the average pooling function
    CAM_RESOLUTION: 2
    CE_WEIGHT: 1.
  #True: CAT
  #False: CAT-KD
  onlyCAT: False
  IF_NORMALIZE: False

# true: convert the normal CNN to our style
if_test: True
device: 0

DATASET:
  AUTO_AUG: False
  CUT_OUT: False

