EXPERIMENT:
  NAME: "resnet32x4,ShuffleV2,fam,ixy->bixy,FE"
  TAG: "resnet32x4,ShuffleV2,fam,3090ti,79.5_res,ixy->bixy,FE"
  PROJECT: "cifar100_baselines_simkd"
DISTILLER:
  TYPE: "SIMKD_test_FE"
  TEACHER: "resnet32x4"
  STUDENT: "ShuffleV2"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.01
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  # WANDB: false
  WANDB: true


# true: convert the normal CNN to our style
device: 1

DATASET:
  AUTO_AUG: False
  CUT_OUT: False

