#256->256
EXPERIMENT:
  NAME: "resnet32x4,resnet8x4,oblation2,001"
  TAG: "resnet32x4,resnet8x4,oblation2,001"
  PROJECT: "cifar100_SFAKD"
DISTILLER:
  TYPE: "SFAKD_oblation2"
  TEACHER: "resnet32x4"
  STUDENT: "resnet8x4"
SOLVER:
  BATCH_SIZE: 64
  EPOCHS: 240
  LR: 0.05
  LR_DECAY_STAGES: [150, 180, 210]
  LR_DECAY_RATE: 0.1
  WEIGHT_DECAY: 0.0005
  MOMENTUM: 0.9
  TYPE: "SGD"

LOG:
  WANDB: false
  # WANDB: true


# true: convert the normal CNN to our style
device: 0

DATASET:
  AUTO_AUG: False
  CUT_OUT: False

SFAKD:
  CUT_OFF: 0.01

